# Generated by Django 2.2.2 on 2020-02-29 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theBlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='userCommentFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commentsUserFK', to='theBlog.Users'),
        ),
    ]
