# Generated by Django 2.2.2 on 2020-02-29 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicValidators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_At', models.DateTimeField(auto_now=True)),
                ('updated_At', models.DateTimeField(auto_now=True)),
                ('userPostsFK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postUserFK', to='theBlog.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_At', models.DateTimeField(auto_now=True)),
                ('updated_At', models.DateTimeField(auto_now=True)),
                ('postCommentsFK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commentsPostFK', to='theBlog.Posts')),
                ('userCommentFK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commentsUserFK', to='theBlog.Users')),
            ],
        ),
    ]
